"""Interactive calibration for the Matches tab tap target.

Single coordinate: the Matches/Conversations icon in Hinge's bottom nav.
Writes matches_coords.json which matches_scan.py reads on every scan.

Re-run anytime the Hinge bottom-nav layout shifts (rare).

Flow:
  1. Screenshot the current state.
  2. Either auto-detect (Hinge's bottom nav has ~5 evenly-spaced icons;
     the speech-bubble Matches icon is conventionally the 3rd or 4th
     from the left) or ask the user for x,y from the saved screenshot.
  3. Tap it, screenshot the result, eyeball that we're on the matches
     view. Save.

The auto-detect is best-effort. If it can't find a clean answer, falls
back to asking the user to read the coord off the saved screenshot.

Prerequisite: Hinge open (any tab), emulator connected via ADB.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import adb
import config


_OUTPUT_FILE = config.BASE_DIR / "matches_coords.json"
_CAL_DIR = config.BASE_DIR

# Heuristic defaults for a 1080x2424 Pixel-class emulator. The bottom nav
# sits in the bottom ~150px strip; icons are roughly evenly spaced. These
# are STARTING GUESSES — calibration writes the real value.
_GUESS_X_BY_NAV_POSITION = {
    # 5-icon nav: Discover · Standouts · Likes-You · Matches · Profile
    1: 108, 2: 324, 3: 540, 4: 756, 5: 972,
}
_GUESS_Y_BOTTOM_NAV = 2310


def _capture(name: str) -> bytes:
    png = adb.screenshot()
    path = _CAL_DIR / f"matches_cal_{name}.png"
    path.write_bytes(png)
    print(f"  saved {path.name}")
    return png


def _prompt_int(label: str, default: int | None = None) -> int:
    suffix = f" [{default}]" if default is not None else ""
    while True:
        s = input(f"{label}{suffix}: ").strip()
        if not s and default is not None:
            return default
        try:
            return int(s)
        except ValueError:
            print("  not an integer, try again")


def _prompt_yes(label: str) -> bool:
    return input(f"{label} [y/N]: ").strip().lower().startswith("y")


def main() -> int:
    adb.check_device()
    print("Matches tab — calibration.")
    print("Make sure Hinge is open (any tab). Press ENTER to continue.")
    input()

    print("\n[Step 1/3] Capturing current state.")
    _capture("00_before")

    print("\n[Step 2/3] Where is the Matches tab icon in the bottom nav?")
    print("  Hinge's bottom nav typically has 5 icons left-to-right.")
    print("  Open matches_cal_00_before.png and count from the left:")
    for pos, x in _GUESS_X_BY_NAV_POSITION.items():
        print(f"    position {pos}: guessed x={x}")
    print(f"  All at y={_GUESS_Y_BOTTOM_NAV}.")
    print("  Type a position number (1-5) to use the guessed x, OR")
    print("  type 'x,y' to enter exact coords read from the screenshot.")
    raw = input("  matches_tab: ").strip()
    if "," in raw:
        x, y = (int(s.strip()) for s in raw.split(","))
    else:
        pos = int(raw) if raw else 4
        x = _GUESS_X_BY_NAV_POSITION.get(pos, 756)
        y = _GUESS_Y_BOTTOM_NAV
    print(f"  Will use matches_tab = ({x}, {y})")

    print("\n[Step 3/3] Tapping and verifying.")
    adb.tap(x, y)
    time.sleep(1.2)
    _capture("01_after_tap")
    print("  Tapped. Look at matches_cal_01_after_tap.png — did Hinge open")
    print("  the matches/conversations view (avatars / 'When you match...' /")
    print("  conversation list)?")
    if not _prompt_yes("  Looks right"):
        print("  Re-run calibration with a different coordinate.")
        return 1

    coords = {
        "_doc": (
            "Generated by calibrate_matches.py. matches_tab is the tap "
            "target for the Matches/Conversations icon in Hinge's bottom "
            "nav. Re-run if Hinge changes its bottom-nav layout."
        ),
        "screen_size": [config.SCREEN_WIDTH, config.SCREEN_HEIGHT],
        "matches_tab": [x, y],
    }
    _OUTPUT_FILE.write_text(json.dumps(coords, indent=2))
    print(f"\nWrote {_OUTPUT_FILE.name}")
    print(f"  matches_tab = ({x}, {y})")
    print("\nTest with:  python matches_scan.py --dry-run")
    return 0


if __name__ == "__main__":
    sys.exit(main())
